sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - extra-cmake-modules
  script:
    - "cd dist/arch/"
    - "ls"
    - "echo $PWD"
    - "makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
