sudo: required

language: cpp

compiler:
  - gcc
  - clang
  - kdeclarative

arch:
  packages:
    - extra-cmake-modules
  script:
    - "cd dist/arch/ && makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
