sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - extra-cmake-modules
    - kdeclarative
    - jack2
    - alsa-utils
    - systemd
    - coreutils
    - qt5-tools
    - xdg-utils
    - python
    - python2-dbus
    - kdelibs
    - plasma-framework
  script:
    - "git clone https://github.com/progwolff/jackman.git"
    - "cd jackman && makepkg -i && cd .."
    - "cd dist/arch/ && makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
