sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - extra-cmake-modules
    - kdeclarative
    - kdelibs
    - jack2
    - alsa-utils
    - systemd
    - coreutils
  script:
    - "git clone https://github.com/progwolff/jackman.git"
    - "cd jackman && makepkg -i && cd .."
    - "cd dist/arch/ && makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
